// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ezvstfgfszlwvexyflyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV6dnN0Zmdmc3psd3ZleHlmbHloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDExNzAyNTUsImV4cCI6MjA1Njc0NjI1NX0.5xNkjAzOwZm_lK7vSWxcWK9t9LuT5k6NkJpB7NzhC_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);